View and create bets on available teams participating in events
crux-bphc/arena-app pull request #4
Opened 2024-12-30 04:42 UTC by soemone

### Please confirm if these details are up to spec (And anything else I missed too)
- Redirects are probably not handled properly
- Pocketbase database auth for superusers may not be handled properly
- The server-side and client-side code may be in the wrong places (I don't think so, but check this anyways)
- The UI is eh. It serves as a template for those who know how to design actual UI/UX

2024-12-30 04:52 UTC, soemone commented
To test, just create some random events and team data, login through auth (change the balance to something other than 0), then interact with the UI

2025-01-02 10:30 UTC, skoriop requested changes
While your PR was functionally fine, it was a bit weirdly organized and could have been simplified quite a bit:
- Instead of keeping all the functions that interact with the database in one huge file, it would be better to keep each relevant function with its API handler. 
- For the superuser authentication, `autoRefreshThreshold` simplifies things a lot (https://pocketbase.io/docs/client-side-sdks/#-personal-opinion)
- Instead of making multiple queries, it's almost always better to use database joins instead, which PocketBase calls "expands" (https://pocketbase.io/docs/working-with-relations/#expanding-relations). It turns out that using these expands with the existing types means that we don't need any extra interfaces at all.
- It would make things more organized to have all the API routes grouped together in a top-level route called `/api`, instead of keeping them with the pages that use them. 

Ideally, I would have asked you to make these changes yourself, but I decided to test some parts of it locally since I wasn't sure if it worked the way I thought, after which it was just faster to commit directly.

Your UI is pretty nice functionally (since it's temporary, I don't think we'll be including that in the code review). However, it is broken because of these changes (I ended up doing most of my testing using API clients instead).

After reviewing my changes, can you add:
- [ ] `GET /api/events` (with an optional query parameter `sport` to filter by) 
- [ ] `GET /api/event/[eventId]/teams`
- [ ] `GET /leaderboad`

2025-01-02 19:21 UTC, skoriop requested changes
Nice work, just two small changes and this should be ready to merge.

2025-01-02 19:21 UTC, skoriop commented on app/src/routes/api/user/events/+server.ts
Filtering by `title` can be removed since we'll be handling searching by event title on the frontend itself.

2025-01-02 19:21 UTC, skoriop commented on app/src/routes/api/user/leaderboard/+server.ts
Can you move the team standings leaderboard part to a separate route like `GET /api/event/[eventId]/standings`?

2025-01-02 19:23 UTC, skoriop commented
As for your point about adding a separate field for teams in events instead of relying on dummy standings, I think it'll be better for that to be a separate PR that I'll do after this is merged.

2025-01-03 08:14 UTC, skoriop commented on app/src/routes/api/user/leaderboard/+server.ts
> +        // NOTE: Should users be filtered for verified status here?
Verified status doesn't really matter (I think all users are verified by default?)

2025-01-03 08:17 UTC, soemone commented on app/src/routes/api/user/leaderboard/+server.ts
> +        // NOTE: Should users be filtered for verified status here?
Yes they're verified by default if you login through google

2025-01-03 09:34 UTC, skoriop approved these changes
Added a few bug fixes, LGTM

2025-01-03 10:31 UTC, merged